baseURL = "http://iamchriscorbin.com/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "I'm Chris"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
  # site default theme ("light", "dark", "auto")
  defaultTheme = "dark"
    images = ["/logo.png"]
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "projects"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Projects"
    url = "/projects/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "hireme"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Hire Me"
    url = "/hireme/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "resume"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Resume"
    url = "/resume/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About Me"
    url = "/about/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 5


 [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/avatar.png"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Hello, I'm Chris!"
      # subtitle shown in home page
      subtitle = "Programmer, Database Wrangler, Automation Enthusiast"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  [params.social]
    GitHub = "chriscorbin"
    Linkedin = "chris-a-corbin"
    Twitter = "@chriscorbin"
    Email = "christopheracorbin@outlook.com"